spring:
  application:
      name: CalendarMeet
  datasource:
    url: jdbc:postgresql://localhost:5432/NeoHack
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: <email_address>
  #  password: <application_password>
  #  properties:
  #    mail.smtp:
  #      auth: true
  #      starttls.enable: true
  #      ssl:
  #        protocols: TLSv1.2
  #        trust: smtp.gmail.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9000




