spring:
  application:
      name: CalendarMeet
  datasource:
    url: jdbc:postgresql://rc1b-wwbzmz7xcyzdmat1.mdb.yandexcloud.net:6432/cnrprod1723112633-team-74053?sslmode=verify-full&sslrootcert=/root/.postgresql/RootCA.pem
    username: cnrprod1723112633-team-74053
    password: hah9oonahshooquiequo1Mae5aiphuaS
    driver-class-name: org.postgresql.Driver
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: <email_address>
  #  password: <application_password>
  #  properties:
  #    mail.smtp:
  #      auth: true
  #      starttls.enable: true
  #      ssl:
  #        protocols: TLSv1.2
  #        trust: smtp.gmail.com
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9000




